import {StyleSheet, Text, View} from 'react-native';
import React from 'react';

interface SaleInterface {
  accid: string;
  accname: string;
  Data: {
    CustomerEmail: string;
    accid: string;
    accname?: any;
    agentid: string;
    agentname: string;
    balamt: string;
    billamt: string;
    bookname: string;
    cityname: string;
    compid: string;
    compname: string;
    days: string;
    entryemail: string;
    entryid: string;
    invdate: string;
    invnochr: string;
    mobile: string;
    prevrecamt: string;
    purcosid: string;
    recamt: string;
    returnamt: string;
    runbalamt: string;
  }[];
}
const SampleScreen = () => {
  const SaleData = [
    {
      purcosid: '10360',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '24121',
      agentid: '1110',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'RB AGENCY',
      invnochr: '1989',
      invdate: '2022-01-22 00:00:00',
      accname: null,
      cityname: 'SURAT',
      mobile: '',
      billamt: '48178',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '48178',
      balamt: '48178',
      days: '248',
      CustomerEmail: '',
    },
    {
      purcosid: '10361',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '24121',
      agentid: '1110',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'RB AGENCY',
      invnochr: '2624',
      invdate: '2022-03-10 00:00:00',
      accname: null,
      cityname: 'SURAT',
      mobile: '',
      billamt: '48006',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '96184',
      balamt: '48006',
      days: '201',
      CustomerEmail: '',
    },
    {
      purcosid: '10359',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '28239',
      agentid: '1018',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '284',
      invdate: '2022-06-23 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '9925615116',
      billamt: '21405',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '21405',
      balamt: '21405',
      days: '96',
      CustomerEmail: '',
    },
    {
      purcosid: '10358',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '5234',
      agentid: '1018',
      bookname: 'POSTAGE EXPENSESS A/C',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '363',
      invdate: '2022-07-01 00:00:00',
      accname: null,
      cityname: '',
      mobile: '',
      billamt: '932',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '17334',
      balamt: '932',
      days: '88',
      CustomerEmail: '',
    },
    {
      purcosid: '10357',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '5234',
      agentid: '1018',
      bookname: 'POSTAGE EXPENSESS A/C',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '218',
      invdate: '2022-06-01 00:00:00',
      accname: null,
      cityname: '',
      mobile: '',
      billamt: '2025',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '16402',
      balamt: '2025',
      days: '118',
      CustomerEmail: '',
    },
    {
      purcosid: '10356',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '5234',
      agentid: '1018',
      bookname: 'POSTAGE EXPENSESS A/C',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '51',
      invdate: '2022-05-01 00:00:00',
      accname: null,
      cityname: '',
      mobile: '',
      billamt: '1093',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '14377',
      balamt: '1093',
      days: '149',
      CustomerEmail: '',
    },
    {
      purcosid: '10355',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '5234',
      agentid: '1018',
      bookname: 'POSTAGE EXPENSESS A/C',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '1985',
      invdate: '2022-03-31 00:00:00',
      accname: null,
      cityname: '',
      mobile: '',
      billamt: '2105',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '13284',
      balamt: '2105',
      days: '180',
      CustomerEmail: '',
    },
    {
      purcosid: '10354',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '5234',
      agentid: '1018',
      bookname: 'POSTAGE EXPENSESS A/C',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '1802',
      invdate: '2022-03-01 00:00:00',
      accname: null,
      cityname: '',
      mobile: '',
      billamt: '2532',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '11179',
      balamt: '2532',
      days: '210',
      CustomerEmail: '',
    },
    {
      purcosid: '10353',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '5234',
      agentid: '1018',
      bookname: 'POSTAGE EXPENSESS A/C',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '1627',
      invdate: '2022-02-01 00:00:00',
      accname: null,
      cityname: '',
      mobile: '',
      billamt: '1964',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '8647',
      balamt: '1964',
      days: '238',
      CustomerEmail: '',
    },
    {
      purcosid: '10352',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '5234',
      agentid: '1018',
      bookname: 'POSTAGE EXPENSESS A/C',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '1449',
      invdate: '2022-01-01 00:00:00',
      accname: null,
      cityname: '',
      mobile: '',
      billamt: '1189',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '6683',
      balamt: '1189',
      days: '269',
      CustomerEmail: '',
    },
    {
      purcosid: '10351',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '5234',
      agentid: '1018',
      bookname: 'POSTAGE EXPENSESS A/C',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '1096',
      invdate: '2021-11-01 00:00:00',
      accname: null,
      cityname: '',
      mobile: '',
      billamt: '5494',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '5494',
      balamt: '5494',
      days: '330',
      CustomerEmail: '',
    },
    {
      purcosid: '10350',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1354',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '1297',
      invdate: '2021-12-25 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '7878515363',
      billamt: '10595',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '311072',
      balamt: '10595',
      days: '276',
      CustomerEmail: '',
    },
    {
      purcosid: '10349',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1354',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '1212',
      invdate: '2021-12-03 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '7878515363',
      billamt: '29147',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '300477',
      balamt: '29147',
      days: '298',
      CustomerEmail: '',
    },
    {
      purcosid: '10348',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1354',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '1191',
      invdate: '2021-11-26 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '7878515363',
      billamt: '30912',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '271330',
      balamt: '30912',
      days: '305',
      CustomerEmail: '',
    },
    {
      purcosid: '10347',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1354',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '960',
      invdate: '2021-09-30 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '7878515363',
      billamt: '28681',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '240418',
      balamt: '28681',
      days: '362',
      CustomerEmail: '',
    },
    {
      purcosid: '10346',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1354',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '857',
      invdate: '2021-09-15 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '7878515363',
      billamt: '26418',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '211737',
      balamt: '26418',
      days: '377',
      CustomerEmail: '',
    },
    {
      purcosid: '10345',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1354',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '793',
      invdate: '2021-09-04 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '7878515363',
      billamt: '40181',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '185319',
      balamt: '40181',
      days: '388',
      CustomerEmail: '',
    },
    {
      purcosid: '10344',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1354',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '750',
      invdate: '2021-08-31 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '7878515363',
      billamt: '9402',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '145138',
      balamt: '9402',
      days: '392',
      CustomerEmail: '',
    },
    {
      purcosid: '10343',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1354',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '723',
      invdate: '2021-08-25 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '7878515363',
      billamt: '44988',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '135736',
      balamt: '44988',
      days: '398',
      CustomerEmail: '',
    },
    {
      purcosid: '10342',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1354',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '628',
      invdate: '2021-08-17 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '7878515363',
      billamt: '28775',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '90748',
      balamt: '28775',
      days: '406',
      CustomerEmail: '',
    },
    {
      purcosid: '10341',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1354',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '538',
      invdate: '2021-08-10 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '7878515363',
      billamt: '28322',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '61973',
      balamt: '28322',
      days: '413',
      CustomerEmail: '',
    },
    {
      purcosid: '10340',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1354',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '434',
      invdate: '2021-07-28 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '7878515363',
      billamt: '33651',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '33651',
      balamt: '33651',
      days: '426',
      CustomerEmail: '',
    },
    {
      purcosid: '10339',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '14998',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '584',
      invdate: '2022-05-25 00:00:00',
      accname: null,
      cityname: 'JODHPUR',
      mobile: '9829024057',
      billamt: '31134',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '234416',
      balamt: '31134',
      days: '125',
      CustomerEmail: '',
    },
    {
      purcosid: '10338',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '14998',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '3271',
      invdate: '2022-02-28 00:00:00',
      accname: null,
      cityname: 'JODHPUR',
      mobile: '9829024057',
      billamt: '67032',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '203282',
      balamt: '67032',
      days: '211',
      CustomerEmail: '',
    },
    {
      purcosid: '10337',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '14998',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '2971',
      invdate: '2022-01-28 00:00:00',
      accname: null,
      cityname: 'JODHPUR',
      mobile: '9829024057',
      billamt: '43092',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '136250',
      balamt: '43092',
      days: '242',
      CustomerEmail: '',
    },
    {
      purcosid: '10335',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '14998',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '2661',
      invdate: '2021-12-21 00:00:00',
      accname: null,
      cityname: 'JODHPUR',
      mobile: '9829024057',
      billamt: '21424',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '45308',
      balamt: '21424',
      days: '280',
      CustomerEmail: '',
    },
    {
      purcosid: '10336',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '14998',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '2762',
      invdate: '2022-01-02 00:00:00',
      accname: null,
      cityname: 'JODHPUR',
      mobile: '9829024057',
      billamt: '47850',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '93158',
      balamt: '47850',
      days: '268',
      CustomerEmail: '',
    },
    {
      purcosid: '10334',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '14998',
      agentid: '5282',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'CHIRAG AGENCY',
      invnochr: '2659',
      invdate: '2021-12-20 00:00:00',
      accname: null,
      cityname: 'JODHPUR',
      mobile: '9829024057',
      billamt: '23884',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '23884',
      balamt: '23884',
      days: '281',
      CustomerEmail: '',
    },
    {
      purcosid: '10333',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1079',
      agentid: '1018',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '151',
      invdate: '2022-03-30 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '9099910331',
      billamt: '35331',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '242618',
      balamt: '35331',
      days: '181',
      CustomerEmail: '',
    },
    {
      purcosid: '10331',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1079',
      agentid: '1018',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '128',
      invdate: '2022-03-09 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '9099910331',
      billamt: '18116',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '191340',
      balamt: '18116',
      days: '202',
      CustomerEmail: '',
    },
    {
      purcosid: '10332',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1079',
      agentid: '1018',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '140',
      invdate: '2022-03-16 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '9099910331',
      billamt: '15947',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '207287',
      balamt: '15947',
      days: '195',
      CustomerEmail: '',
    },
    {
      purcosid: '10330',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1079',
      agentid: '1018',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '111',
      invdate: '2022-01-28 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '9099910331',
      billamt: '24742',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '173224',
      balamt: '24742',
      days: '242',
      CustomerEmail: '',
    },
    {
      purcosid: '10329',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1079',
      agentid: '1018',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '101',
      invdate: '2022-01-25 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '9099910331',
      billamt: '23525',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '148482',
      balamt: '23525',
      days: '245',
      CustomerEmail: '',
    },
    {
      purcosid: '10327',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1079',
      agentid: '1018',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '92',
      invdate: '2022-01-20 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '9099910331',
      billamt: '1536',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '103624',
      balamt: '1536',
      days: '250',
      CustomerEmail: '',
    },
    {
      purcosid: '10328',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1079',
      agentid: '1018',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '98',
      invdate: '2022-01-22 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '9099910331',
      billamt: '21333',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '124957',
      balamt: '21333',
      days: '248',
      CustomerEmail: '',
    },
    {
      purcosid: '10326',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1079',
      agentid: '1018',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '89',
      invdate: '2022-01-18 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '9099910331',
      billamt: '30619',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '102088',
      balamt: '30619',
      days: '252',
      CustomerEmail: '',
    },
    {
      purcosid: '10325',
      entryid: '0',
      entryemail: 'dssnvs@gmail.com',
      compid: '2048',
      accid: '1079',
      agentid: '1018',
      bookname: 'PURCHASE INVOICE',
      compname: 'GAURI CREATION',
      agentname: 'DIRECT',
      invnochr: '88',
      invdate: '2022-01-18 00:00:00',
      accname: null,
      cityname: 'AHMEDABAD',
      mobile: '9099910331',
      billamt: '1271',
      prevrecamt: '0',
      returnamt: '0',
      recamt: '0',
      runbalamt: '71469',
      balamt: '1271',
      days: '252',
      CustomerEmail: '',
    },
  ];

  //   var results = SaleData.reduce(function (results, org) {
  //     (
  //         results[org.accid] = results[org.accid] || []
  //         ).push(org);
  //     // (results[org.accid] = results[org.accid] || []).push(org);
  //     return results;
  //   }, {});

  //   console.log('results()', results);

  const transformed = SaleData.reduce((acc, current) => {
    const accId = current.accid;

    // Get or initialize the accumulator object for this accid
    let accObj = acc.find(obj => obj.accid === accId);
    if (!accObj) {
      accObj = {
        accname: '',
        data: [],
        Total: 0,
      };
      acc.push(accObj);
    }

    // Add current item to data array
    accObj.data.push({
      ...current,
    });

    // Sum billamt to calculate total
    accObj.Total += parseInt(current.billamt);
    accObj.accname = current.accname;
    accObj.accid = current.accid;

    return acc;
  }, []);

  console.log('transformed >>>>>>>>>', transformed[0]);

  //   const NewSaleData = Array();
  //   let Accid: string;

  //   SaleData.map(data => {
  //     let Obj: SaleInterface;
  //     if (data.accid !== Accid) {
  //       Accid = data.accid;

  //       Obj.accid = data.accid;
  //       Obj.accname = data.accname!;
  //       Obj.Data.push(data);
  //       console.log('data', data);
  //     }
  //   });

  return (
    <View>
      <Text>SampleScreen</Text>
    </View>
  );
};

export default SampleScreen;

const styles = StyleSheet.create({});
